/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Coords } from "./types/Coords";
import { LogicFlowConnection } from "./components/logic-flow-connection/logic-flow-connection";
import { Element } from "@stencil/core";
import { ViewContext } from "./types/ViewContext";
export { Coords } from "./types/Coords";
export { LogicFlowConnection } from "./components/logic-flow-connection/logic-flow-connection";
export { Element } from "@stencil/core";
export { ViewContext } from "./types/ViewContext";
export namespace Components {
    interface LogicFlowConnection {
        "connectors": Set<HTMLLogicFlowConnectorElement>;
        "end": Coords;
        "isVisible": boolean;
        "start": Coords;
        "type": 'input' | 'output';
    }
    interface LogicFlowConnector {
        "connectingConnector": LogicFlowConnector | null;
        "connections": LogicFlowConnection[];
        "getNode": () => Promise<HTMLLogicFlowNodeElement>;
        "onConnection": (
    sourceConnector: HTMLLogicFlowConnectorElement,
    // targetConnector: HTMLLogicFlowConnectorElement,
  ) => Promise<boolean>;
        "onDisconnection": (
    sourceConnector: HTMLLogicFlowConnectorElement,
    // targetConnector: HTMLLogicFlowConnectorElement,
  ) => Promise<boolean>;
        "onUpdateFromConnectedNode": (
    connector: HTMLLogicFlowConnectorElement,
    node: HTMLLogicFlowNodeElement,
    data: any,
  ) => Promise<void>;
        "type": 'input' | 'output';
    }
    interface LogicFlowNode {
        "getConnectedNodes": (type?: "input" | "output" | "both") => Promise<void>;
        "getConnectors": (type?: "input" | "output" | "both") => Promise<Set<HTMLLogicFlowConnectorElement>>;
        "getInputConnectors": () => Promise<NodeListOf<Element>>;
        "getOutputConnectors": () => Promise<NodeListOf<Element>>;
        "isVisible": boolean;
        "notifyConnectedConnectors": (type: "input" | "output" | "both", data: any) => Promise<void>;
        "position": Coords;
        "startX": number;
        "startY": number;
        "type": string;
    }
    interface LogicFlowViewport {
        "connectorSnappingDistance": number;
        "cursors": Record<string, string>;
        "getContext": () => Promise<ViewContext>;
        "gridBgColor": string;
        "gridLineColor": string;
        "gridSize": number;
        "gridType": 'line' | 'dot';
        "maxZoom": number;
        "minZoom": number;
        "screenToWorldCoords": (screenCoords: Coords) => Promise<Coords>;
        "showGrid": boolean;
        "snapToGrid": boolean;
        "zoomSpeed": number;
    }
}
export interface LogicFlowNodeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLogicFlowNodeElement;
}
declare global {
    interface HTMLLogicFlowConnectionElement extends Components.LogicFlowConnection, HTMLStencilElement {
    }
    var HTMLLogicFlowConnectionElement: {
        prototype: HTMLLogicFlowConnectionElement;
        new (): HTMLLogicFlowConnectionElement;
    };
    interface HTMLLogicFlowConnectorElement extends Components.LogicFlowConnector, HTMLStencilElement {
    }
    var HTMLLogicFlowConnectorElement: {
        prototype: HTMLLogicFlowConnectorElement;
        new (): HTMLLogicFlowConnectorElement;
    };
    interface HTMLLogicFlowNodeElementEventMap {
        "notifyConnectors": any;
    }
    interface HTMLLogicFlowNodeElement extends Components.LogicFlowNode, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLogicFlowNodeElementEventMap>(type: K, listener: (this: HTMLLogicFlowNodeElement, ev: LogicFlowNodeCustomEvent<HTMLLogicFlowNodeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLogicFlowNodeElementEventMap>(type: K, listener: (this: HTMLLogicFlowNodeElement, ev: LogicFlowNodeCustomEvent<HTMLLogicFlowNodeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLogicFlowNodeElement: {
        prototype: HTMLLogicFlowNodeElement;
        new (): HTMLLogicFlowNodeElement;
    };
    interface HTMLLogicFlowViewportElement extends Components.LogicFlowViewport, HTMLStencilElement {
    }
    var HTMLLogicFlowViewportElement: {
        prototype: HTMLLogicFlowViewportElement;
        new (): HTMLLogicFlowViewportElement;
    };
    interface HTMLElementTagNameMap {
        "logic-flow-connection": HTMLLogicFlowConnectionElement;
        "logic-flow-connector": HTMLLogicFlowConnectorElement;
        "logic-flow-node": HTMLLogicFlowNodeElement;
        "logic-flow-viewport": HTMLLogicFlowViewportElement;
    }
}
declare namespace LocalJSX {
    interface LogicFlowConnection {
        "connectors"?: Set<HTMLLogicFlowConnectorElement>;
        "end"?: Coords;
        "isVisible"?: boolean;
        "start"?: Coords;
        "type"?: 'input' | 'output';
    }
    interface LogicFlowConnector {
        "connectingConnector"?: LogicFlowConnector | null;
        "connections"?: LogicFlowConnection[];
        "onConnection"?: (
    sourceConnector: HTMLLogicFlowConnectorElement,
    // targetConnector: HTMLLogicFlowConnectorElement,
  ) => Promise<boolean>;
        "onDisconnection"?: (
    sourceConnector: HTMLLogicFlowConnectorElement,
    // targetConnector: HTMLLogicFlowConnectorElement,
  ) => Promise<boolean>;
        "onUpdateFromConnectedNode"?: (
    connector: HTMLLogicFlowConnectorElement,
    node: HTMLLogicFlowNodeElement,
    data: any,
  ) => Promise<void>;
        "type"?: 'input' | 'output';
    }
    interface LogicFlowNode {
        "isVisible"?: boolean;
        "onNotifyConnectors"?: (event: LogicFlowNodeCustomEvent<any>) => void;
        "position"?: Coords;
        "startX"?: number;
        "startY"?: number;
        "type"?: string;
    }
    interface LogicFlowViewport {
        "connectorSnappingDistance"?: number;
        "cursors"?: Record<string, string>;
        "gridBgColor"?: string;
        "gridLineColor"?: string;
        "gridSize"?: number;
        "gridType"?: 'line' | 'dot';
        "maxZoom"?: number;
        "minZoom"?: number;
        "showGrid"?: boolean;
        "snapToGrid"?: boolean;
        "zoomSpeed"?: number;
    }
    interface IntrinsicElements {
        "logic-flow-connection": LogicFlowConnection;
        "logic-flow-connector": LogicFlowConnector;
        "logic-flow-node": LogicFlowNode;
        "logic-flow-viewport": LogicFlowViewport;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "logic-flow-connection": LocalJSX.LogicFlowConnection & JSXBase.HTMLAttributes<HTMLLogicFlowConnectionElement>;
            "logic-flow-connector": LocalJSX.LogicFlowConnector & JSXBase.HTMLAttributes<HTMLLogicFlowConnectorElement>;
            "logic-flow-node": LocalJSX.LogicFlowNode & JSXBase.HTMLAttributes<HTMLLogicFlowNodeElement>;
            "logic-flow-viewport": LocalJSX.LogicFlowViewport & JSXBase.HTMLAttributes<HTMLLogicFlowViewportElement>;
        }
    }
}
